trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    docker compose version
  displayName: Check Docker Compose

- script: |
    docker compose build
  displayName: Build Containers

- script: |
    docker compose up -d
  displayName: Start Containers

- script: |
    docker compose ps
  displayName: Check Containers

- script: |
    docker compose logs
  displayName: Show Container Logs

- script: |
    docker compose down
  displayName: Stop Containers
