trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    docker compose \
      -f "$(Build.SourcesDirectory)/docker-compose.yml" \
      build
  displayName: Build Containers


- script: |
    docker compose \
      -f "$(Build.SourcesDirectory)/docker-compose.yml" \
      up -d
  displayName: Start Containers


- script: |
    echo "Running containers:"
    docker compose \
      -f "$(Build.SourcesDirectory)/docker-compose.yml" \
      ps
  displayName: Check Containers


- script: |
    echo "Testing API container..."
    curl -f http://localhost:3000

    echo ""
    echo "API test successful."
  displayName: Test API


- script: |
    echo "Testing Web container..."
    curl -f http://localhost:8080

    echo ""
    echo "Web test successful."
  displayName: Test Web


- script: |
    echo "Container logs:"
    docker compose \
      -f "$(Build.SourcesDirectory)/docker-compose.yml" \
      logs
  displayName: Show Container Logs


- script: |
    docker compose \
      -f "$(Build.SourcesDirectory)/docker-compose.yml" \
      down
  displayName: Stop Containers
